#!/bin/bash
# Usage: opener filename
set -e
shopt -s nocasematch

case "$1" in
*.ogg | *.mp3 | *.opus | *.mkv | *.wav | *.avi | *.flac | *.wma | *.mp4 | \
*.m3u | *.m4a | *.m4b | *.vob)
	mpv --quiet --no-video "$1"
	;;
*)
	less "$1"
	;;
esac
